### ISSUE TITLE
[Request] Ability to turn front wheels without accelerating

### ISSUE THREAD

**Issue by lavanoid** [bskari/pi-rc#11]
As the title states, would it be possible to turn the front directional wheels without accelerating? Would be useful for turning the vehicle without "breaking the speed limit", I seem to crash my car when I accelerate while turning - being able to slow down on a turn would be great!

Sorry for not paying much attention on this project lately, I've had college and I've been diagnosed with depression as well as anxiety so I haven't been able to do much recently. We still need to sort out that PIP package thing that we were planning to do.

Thanks again!

**Comment by bskari** [comment]
Should be working. I don't have a PiFace to test with, but I edited the code and ran it through a linter, so the synax should be good. I don't know what the command codes for left and right are for the Ford Mustang; you'll need to check that yourself.

Don't worry about being busy with your own stuff. It's important to take care of yourself before you start thinking about anything else; that's one thing I've learned several times. I've been busy with my own stuff, which is why this took me so long.

As for the Python package, I've been thinking I might just make a separate GitHub project. I know at least a few people are already using this code, and I think it would be easier to start over. Also, it would be cool if I could include the ability to broadcast FM radio, since we'll be partly there anyway. I also saw an article about sending images over SSTV, but that's probably getting too far ahead.

**Comment by lavanoid** [comment]
Thank you! I'll be sure to make changes to the PiFaceCAD script if needed, and I'll push them to your repo. I don't mind the delay in response time, we all have lives of our own ;). Thanks for your understanding.

As for the new project that you plan on starting - I'll try to contribute towards it if I can, as I find this sort of stuff really fascinating and I really appreciate your work. On my current project, I haft to switch between Pi-RC and PiFM to use each of their features, so I guess it would be pretty cool to have everything put into a single application.

Not sure why either, but both Pi-RC and PiFM break audio on the audio jack (not sure about HDMI) - it seems to break pulse audio too (maybe the cause?).

Do you think it's possible to use any other GPIO pins, instead of just GPIO 4? If Pi-RC and PiFM was put into a single app, it would be even better to be able to use both features at the same time (by sending signals on 2 separate pins).

Sending images over SSTV.... I think it would be a great addition (hey, its another feature - why not? Right?). 

I was thinking if it was possible to add an RC receiver to another Pi, then attach the motor cables to the GPIO's and treat them as "buttons". I could use one Pi to send signals (maybe in morse code?) through Pi-RC, then the other Pi can keep checking for "button presses" and decode it. Haven't tried it, however - I have no more receivers.

I had removed a receiver from a RC car, then soldered headers onto it (which I had taken from a old  PC motherboard) so I could use it in my robot project. Turns out that the L298N H-Bridge doesn't give out much power to the motors (I believe it's because it was designed for a 12v power supply not a 4v/5v one), so I'm using the RC receiver instead.

 I'll show you more info about it, sometime - if you want? I let a friend from America control it through the internet once, and he could see what was happening though a Google Hangouts video chat.
