### ISSUE TITLE
2.4 GHz?

### ISSUE THREAD

**Issue by anishanne** [bskari/pi-rc#27]
My RC car runs on 2.4 GHz, what should I do?

**Comment by Gideon357** [comment]
@anishanne I have this issue too. 2.4 GHz is 2400 MHz, which seems wrong for watch.html. Maybe someone else knows. Have you tried 24 MHz or 2400 MHz?

**Comment by bskari** [comment]
Unfortunately, due to how the signal is generated, the Pi can't generate signals over 250 MHz. In order to get a consistent signal, we need to use the Pi's DMA controller, which is clocked at 500 MHz. Because you need to turn the pin off and on to generate a signal, the fastest you can do as 250 MHz. 2.4 GHz will likely never be possible.
